services:
  - type: web
    name: gpt-to-svg-gcode-ai
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: "docker build -t my-python-app ."
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ORGANIZATION
        sync: false
      - key: OPENAI_PROJECT
        sync: false
      - key: CONVERTIO_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: CONVERTIO_URL
        sync: false
      
